# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 73)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.oneBitArea_2 = QtWidgets.QVBoxLayout()
        self.oneBitArea_2.setObjectName("oneBitArea_2")
        self.commandArea_3 = QtWidgets.QFrame(self.frame)
        self.commandArea_3.setMinimumSize(QtCore.QSize(0, 0))
        self.commandArea_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.commandArea_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.commandArea_3.setObjectName("commandArea_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.commandArea_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.path_2 = QtWidgets.QLabel(self.commandArea_3)
        self.path_2.setMinimumSize(QtCore.QSize(0, 18))
        self.path_2.setObjectName("path_2")
        self.horizontalLayout_6.addWidget(self.path_2)
        self.commandEntry_2 = QtWidgets.QLineEdit(self.commandArea_3)
        self.commandEntry_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.commandEntry_2.setStyleSheet("padding:0;\n"
"border-color: rgb(170, 170, 127);")
        self.commandEntry_2.setObjectName("commandEntry_2")
        self.horizontalLayout_6.addWidget(self.commandEntry_2)
        self.oneBitArea_2.addWidget(self.commandArea_3)
        self.outputArea_2 = QtWidgets.QFrame(self.frame)
        self.outputArea_2.setMinimumSize(QtCore.QSize(0, 25))
        self.outputArea_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputArea_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputArea_2.setObjectName("outputArea_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.outputArea_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.output_2 = QtWidgets.QLabel(self.outputArea_2)
        self.output_2.setMinimumSize(QtCore.QSize(0, 5))
        self.output_2.setText("")
        self.output_2.setWordWrap(False)
        self.output_2.setObjectName("output_2")
        self.verticalLayout_3.addWidget(self.output_2)
        self.oneBitArea_2.addWidget(self.outputArea_2)
        self.verticalLayout_2.addLayout(self.oneBitArea_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.path_2.setText(_translate("Form", "C:/User/jack/hello/Root#"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
