# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.WinFrame = QtWidgets.QFrame(self.centralwidget)
        self.WinFrame.setMinimumSize(QtCore.QSize(250, 250))
        self.WinFrame.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"")
        self.WinFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.WinFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WinFrame.setObjectName("WinFrame")
        self.WinFrameLayout = QtWidgets.QVBoxLayout(self.WinFrame)
        self.WinFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.WinFrameLayout.setSpacing(7)
        self.WinFrameLayout.setObjectName("WinFrameLayout")
        self.titleBar = QtWidgets.QFrame(self.WinFrame)
        self.titleBar.setMinimumSize(QtCore.QSize(0, 50))
        self.titleBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.titleBar.setAutoFillBackground(False)
        self.titleBar.setStyleSheet("background-color:rgba(221, 220, 219, 0);\n"
"border-radius:10px;")
        self.titleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLabel = QtWidgets.QFrame(self.titleBar)
        self.titleLabel.setStyleSheet("background-color:rgba(221, 200, 219, 180);\n"
"border-radius:10px;")
        self.titleLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.titleLabel)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(15, 0, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.titleLabel)
        self.label.setStyleSheet("color: rgb(0, 85, 127);\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,0,0,0);")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayout.addWidget(self.titleLabel)
        self.titleBtns = QtWidgets.QFrame(self.titleBar)
        self.titleBtns.setStyleSheet("background-color:rgba(221, 200, 219, 180);\n"
"border-radius:10px;")
        self.titleBtns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleBtns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBtns.setObjectName("titleBtns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleBtns)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnMaxmize = QtWidgets.QPushButton(self.titleBtns)
        self.btnMaxmize.setMinimumSize(QtCore.QSize(20, 20))
        self.btnMaxmize.setMaximumSize(QtCore.QSize(20, 20))
        self.btnMaxmize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMaxmize.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(145, 217, 0);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(180, 217, 0);\n"
"}\n"
"")
        self.btnMaxmize.setText("")
        self.btnMaxmize.setObjectName("btnMaxmize")
        self.horizontalLayout_2.addWidget(self.btnMaxmize)
        self.btnMinimize = QtWidgets.QPushButton(self.titleBtns)
        self.btnMinimize.setMinimumSize(QtCore.QSize(20, 20))
        self.btnMinimize.setMaximumSize(QtCore.QSize(20, 20))
        self.btnMinimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMinimize.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnMinimize.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgb(241, 241, 0);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(241, 200, 0);\n"
"}\n"
"")
        self.btnMinimize.setText("")
        self.btnMinimize.setObjectName("btnMinimize")
        self.horizontalLayout_2.addWidget(self.btnMinimize)
        self.btnClose = QtWidgets.QPushButton(self.titleBtns)
        self.btnClose.setMinimumSize(QtCore.QSize(20, 20))
        self.btnClose.setMaximumSize(QtCore.QSize(20, 20))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClose.setStyleSheet("QPushButton{\n"
"background-color: rgb(244, 68, 9);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"  background-color: rgb(255, 80, 0);\n"
"}")
        self.btnClose.setText("")
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_2.addWidget(self.btnClose)
        self.horizontalLayout.addWidget(self.titleBtns)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 2)
        self.WinFrameLayout.addWidget(self.titleBar)
        self.frame = QtWidgets.QFrame(self.WinFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("QScrollArea{\n"
"  \n"
"    background-color: rgb(170, 170, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"\n"
"   border: none;\n"
"\n"
"    background: rgb(45, 45, 68);\n"
"\n"
"    width: 14px;\n"
"\n"
"    margin: 15px 0 15px 0;\n"
"\n"
"    border-radius: 0px;\n"
"\n"
" }\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:vertical {    \n"
"\n"
"    background-color: rgb(80, 80, 122);\n"
"\n"
"    min-height: 30px;\n"
"\n"
"    border-radius: 7px;\n"
"\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{    \n"
"\n"
"    background-color:rgb(80, 90, 122);\n"
"\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed {    \n"
"\n"
"    background-color: rgb(80, 100, 102);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"\n"
"    border: none;\n"
"   background-color: rgb(59, 59, 90);\n"
"   height: 15px;\n"
"\n"
"    border-top-left-radius: 7px;\n"
"\n"
"    border-top-right-radius: 7px;\n"
"\n"
"   subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"\n"
"     background-color: rgb(59, 70, 90);\n"
"\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"\n"
"    background-color: rgb(59, 80, 95);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"\n"
"    border: none;\n"
"\n"
"    background-color: rgb(59, 59, 90);\n"
"\n"
"    height: 15px;\n"
"\n"
"    border-bottom-left-radius: 7px;\n"
"\n"
"    border-bottom-right-radius: 7px;\n"
"\n"
"    subcontrol-position: bottom;\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"\n"
"    background-color: rgb(59, 70, 90);\n"
"\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"\n"
"   background-color: rgb(59, 80, 95);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"\n"
"       border: none;\n"
"\n"
"    background: rgb(45, 45, 68);\n"
"\n"
"    height: 14px;\n"
"\n"
"    margin: 0 15px 0px 15px;\n"
"\n"
"    border-radius: 0px;\n"
"\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"\n"
"    background-color: rgb(80, 80, 122);\n"
"\n"
"    min-width: 30px;\n"
"\n"
"    border-radius: 7px;\n"
"\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"\n"
"    border: none;\n"
"\n"
"    background-color: rgb(59, 59, 90);\n"
"\n"
"    width: 15px;\n"
"\n"
"    border-top-right-radius: 7px;\n"
"\n"
"    border-bottom-right-radius: 7px;\n"
"\n"
"    subcontrol-position: right;\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"\n"
"    border: none;\n"
"\n"
"    background-color: rgb(59, 59, 90);\n"
"\n"
"    border-top-left-radius: 7px;\n"
"\n"
"    width:15px;\n"
"\n"
"    border-bottom-left-radius: 7px;\n"
"\n"
"    subcontrol-position: left;\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"\n"
"{\n"
"\n"
"background: none;\n"
"\n"
"}\n"
"\n"
"ScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"\n"
"{\n"
"\n"
"background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"\n"
"   background-color:rgb(112, 10, 255);\n"
"\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"\n"
"    background-color: rgb(112, 10, 205);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"\n"
"    background-color: rgb(255, 50, 10);\n"
"\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"\n"
"    background-color:rgb(255, 50, 0);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"\n"
"    background-color: rgb(255, 50, 10);\n"
"\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"\n"
"    background-color: rgb(255, 50, 0);\n"
"\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 596, 493))
        self.scrollContent.setObjectName("scrollContent")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.scrollContent)
        self.verticalLayout_61.setSpacing(0)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_61.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollContent)
        self.horizontalLayout_4.addWidget(self.scrollArea)
        self.WinFrameLayout.addWidget(self.frame)
        self.WinFrameLayout.setStretch(0, 1)
        self.verticalLayout.addWidget(self.WinFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "My App"))
        self.btnMaxmize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btnMinimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btnClose.setToolTip(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
