# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(425, 73)
        Frame.setMinimumSize(QtCore.QSize(0, 73))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.oneBitArea_2 = QtWidgets.QVBoxLayout()
        self.oneBitArea_2.setObjectName("oneBitArea_2")
        self.commandArea_3 = QtWidgets.QFrame(self.frame)
        self.commandArea_3.setMinimumSize(QtCore.QSize(0, 38))
        self.commandArea_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.commandArea_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.commandArea_3.setObjectName("commandArea_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.commandArea_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.path_2 = QtWidgets.QLabel(self.commandArea_3)
        self.path_2.setMinimumSize(QtCore.QSize(0, 18))
        self.path_2.setObjectName("path_2")
        self.horizontalLayout_6.addWidget(self.path_2)
        self.commandEntry_2 = QtWidgets.QLineEdit(self.commandArea_3)
        self.commandEntry_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.commandEntry_2.setStyleSheet("padding:0;")
        self.commandEntry_2.setObjectName("commandEntry_2")
        self.horizontalLayout_6.addWidget(self.commandEntry_2)
        self.oneBitArea_2.addWidget(self.commandArea_3)
        self.outputArea_2 = QtWidgets.QFrame(self.frame)
        self.outputArea_2.setMinimumSize(QtCore.QSize(0, 25))
        self.outputArea_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputArea_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputArea_2.setObjectName("outputArea_2")
        self.output_2 = QtWidgets.QLabel(self.outputArea_2)
        self.output_2.setGeometry(QtCore.QRect(50, 10, 47, 13))
        self.output_2.setMinimumSize(QtCore.QSize(0, 13))
        self.output_2.setWordWrap(False)
        self.output_2.setObjectName("output_2")
        self.oneBitArea_2.addWidget(self.outputArea_2)
        self.horizontalLayout_2.addLayout(self.oneBitArea_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.path_2.setText(_translate("Frame", "C:/User/jack/hello/Root#"))
        self.output_2.setText(_translate("Frame", " sfsdfffd\n"
"dsdsfds fdfdsf"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
